# ============================================================
# Scientific question / 科学问题:
#   Auto-emit a complete data dictionary so reviewers can audit every
#   variable used by manuscript_v2 without diving into the code.
#   自动生成数据字典，便于审稿人快速核对每个变量含义。
#
# Objective / 分析目标:
#   - Scan data/raw/, data/derived/, results/tables/ for CSV/parquet.
#   - For each file, emit a YAML schema describing column name, type,
#     range, source script and notes.
#   - Aggregate into data_dictionary/variables_master.csv with one row
#     per (file, variable).
#
# Input data / 输入数据:
#   Any file under data/raw, data/derived, results/tables, results/diagnostics.
#
# Main workflow / 主要流程:
#   1. Walk directories.
#   2. Open each table (csv via fread, parquet via arrow).
#   3. Sample summary stats; build YAML schema if missing.
#   4. Concatenate into master CSV.
#
# Expected output / 预期输出:
#   data_dictionary/schema_<filename>.yaml
#   data_dictionary/variables_master.csv
#   data_dictionary/README.md (only if missing)
#
# Main packages / 主要包: data.table, arrow, yaml, fs, glue.
# Output directory / 输出路径: data_dictionary/.
# ============================================================

suppressPackageStartupMessages({
  library(data.table)
  library(arrow)
  library(yaml)
  library(fs)
  library(glue)
})

source(file.path("code", "utils", "utils_data.R"))

ensure_dir(v2_path("data_dictionary"))

# ---- 0. README if absent ----------------------------------------------------
readme_path <- v2_path("data_dictionary", "README.md")
if (!file.exists(readme_path)) {
  cat("# Data dictionary\n\n",
      "This directory is auto-generated by `code/36_data_dictionary_export.R`.\n",
      "Edit the `description` field of any `schema_*.yaml` to add human-readable\n",
      "notes; the script preserves existing descriptions on re-run.\n\n",
      "`variables_master.csv` is the canonical join of all schemas (one row per\n",
      "(file, variable) pair).\n",
      file = readme_path)
}

# ---- 1. Helpers -------------------------------------------------------------
load_any <- function(path) {
  ext <- tolower(tools::file_ext(path))
  tryCatch(switch(ext,
    csv = fread(path, encoding = "UTF-8", nrows = 50000),
    parquet = arrow::read_parquet(path),
    fst = if (requireNamespace("fst", quietly = TRUE))
            fst::read_fst(path, as.data.table = TRUE) else NULL,
    NULL
  ), error = function(e) NULL)
}

guess_unit <- function(name) {
  if (grepl("^lat|latitude", name, ignore.case = TRUE)) return("°N")
  if (grepl("^lon|longitude", name, ignore.case = TRUE)) return("°E")
  if (grepl("temp|tas|warming", name, ignore.case = TRUE)) return("°C")
  if (grepl("precip|prec", name, ignore.case = TRUE)) return("mm")
  if (grepl("velocity", name, ignore.case = TRUE)) return("km/decade")
  if (grepl("area", name, ignore.case = TRUE)) return("km²")
  if (grepl("year", name, ignore.case = TRUE)) return("year")
  if (grepl("hours", name, ignore.case = TRUE)) return("hours")
  if (grepl("_z$", name)) return("z-score")
  if (grepl("^log_", name)) return("log()")
  ""
}

build_schema <- function(path) {
  df <- load_any(path)
  if (is.null(df)) return(NULL)
  setDT(df)
  schema <- list(
    file        = basename(path),
    path        = path,
    rows_sampled = nrow(df),
    columns     = ncol(df),
    variables   = lapply(names(df), function(col) {
      v <- df[[col]]
      list(
        name        = col,
        type        = class(v)[1],
        n_missing   = sum(is.na(v)),
        unique      = if (is.numeric(v)) NA_integer_ else uniqueN(v),
        min         = if (is.numeric(v)) suppressWarnings(min(v, na.rm = TRUE)) else NULL,
        max         = if (is.numeric(v)) suppressWarnings(max(v, na.rm = TRUE)) else NULL,
        unit        = guess_unit(col),
        description = ""   # user-editable
      )
    })
  )
  schema
}

merge_existing <- function(new_schema, existing_path) {
  if (!file.exists(existing_path)) return(new_schema)
  old <- yaml::read_yaml(existing_path)
  if (is.null(old$variables)) return(new_schema)
  desc_by_name <- setNames(
    vapply(old$variables, function(v) v$description %||% "", character(1)),
    vapply(old$variables, function(v) v$name, character(1))
  )
  for (i in seq_along(new_schema$variables)) {
    nm <- new_schema$variables[[i]]$name
    if (nm %in% names(desc_by_name) && nzchar(desc_by_name[[nm]])) {
      new_schema$variables[[i]]$description <- desc_by_name[[nm]]
    }
  }
  new_schema
}

scan_dir <- function(dir, glob = c("*.csv", "*.parquet", "*.fst")) {
  if (!dir.exists(dir)) return(character(0))
  unlist(lapply(glob, function(g) list.files(dir, pattern = utils::glob2rx(g),
                                              full.names = TRUE,
                                              recursive  = FALSE)))
}

# ---- 2. Walk and emit -------------------------------------------------------
targets_to_scan <- c(
  path_raw(),
  path_derived(),
  path_tables(),
  path_diagnostics(),
  path_sensitivity(),
  path_forecasts()
)

all_rows <- list()

for (dir in targets_to_scan) {
  files <- scan_dir(dir)
  for (f in files) {
    sch <- build_schema(f)
    if (is.null(sch)) next
    sch_path <- v2_path("data_dictionary",
                         paste0("schema_", tools::file_path_sans_ext(basename(f)),
                                ".yaml"))
    sch <- merge_existing(sch, sch_path)
    yaml::write_yaml(sch, sch_path)
    for (v in sch$variables) {
      all_rows[[length(all_rows) + 1L]] <- data.table::data.table(
        file = sch$file, variable = v$name, type = v$type,
        n_missing = v$n_missing %||% NA_integer_,
        min = v$min %||% NA_real_, max = v$max %||% NA_real_,
        unit = v$unit, description = v$description
      )
    }
  }
}

master <- data.table::rbindlist(all_rows, fill = TRUE)
fwrite(master, v2_path("data_dictionary", "variables_master.csv"))
message(glue("[36] wrote {nrow(master)} rows to variables_master.csv ",
              "(scanned {length(unique(master$file))} files)."))

dump_session_info(path_logs("36_data_dictionary_export_sessionInfo.txt"))
message("[36] done.")
